export const ACTION_CHANGE_FIRST_NAME = "ACTION_CHANGE_FIRST_NAME";
export const ACTION_CHANGE_SECOND_NAME = "ACTION_CHANGE_SECOND_NAME";
export const ACTION_CHANGE_THIRD_NAME = "ACTION_CHANGE_THIRD_NAME";
export const ACTION_CHANGE_AGE = "ACTION_CHANGE_AGE";
